{% set version = '1.3.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stm/stm_{{ version }}.tar.gz
  sha256: 9b8f68c1151635f98d07bd379c454b7ca5f13e7c4efe61707122c560422631ac

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.11.3
    - r-rcpparmadillo
    - r-data.table
    - r-glmnet
    - r-lda
    - r-matrixstats
    - r-quadprog
    - r-quanteda
    - r-slam
    - r-stringr
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=0.11.3
    - r-rcpparmadillo
    - r-data.table
    - r-glmnet
    - r-lda
    - r-matrixstats
    - r-quadprog
    - r-quanteda
    - r-slam
    - r-stringr

test:
  commands:
    - $R -e "library('stm')"           # [not win]
    - "\"%R%\" -e \"library('stm')\""  # [win]

about:
  home: http://structuraltopicmodel.com
  license: MIT
  summary: The Structural Topic Model (STM) allows researchers  to estimate topic models with
    document-level covariates.  The package also includes tools for model selection,
    visualization, and estimation of topic-covariate regressions. Methods developed
    in Roberts et al (2014) <doi:10.1111/ajps.12103> and  Roberts et al (2016) <doi:10.1080/01621459.2016.1141684>.
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - stevierene82

# Package: stm
# Type: Package
# Title: Estimation of the Structural Topic Model
# Version: 1.3.3
# Date: 2018-1-26
# Author: Margaret Roberts [aut, cre],  Brandon Stewart [aut, cre], Dustin Tingley [aut, cre], Kenneth Benoit [ctb]
# Maintainer: Brandon Stewart <bms4@princeton.edu>
# Depends: R (>= 3.2.2)
# LinkingTo: Rcpp, RcppArmadillo
# Imports: matrixStats, splines, slam, lda, quanteda, stringr, Matrix, glmnet, Rcpp (>= 0.11.3), grDevices, graphics, stats, utils, data.table, quadprog, parallel, methods
# Suggests: igraph, SnowballC, tm (>= 0.6), huge, clue, wordcloud, KernSmooth, NLP, LDAvis, geometry, Rtsne, testthat, rsvd
# LazyData: yes
# Description: The Structural Topic Model (STM) allows researchers  to estimate topic models with document-level covariates.  The package also includes tools for model selection, visualization, and estimation of topic-covariate regressions. Methods developed in Roberts et al (2014) <doi:10.1111/ajps.12103> and  Roberts et al (2016) <doi:10.1080/01621459.2016.1141684>.
# License: MIT + file LICENSE
# URL: http://structuraltopicmodel.com
# BugReports: https://github.com/bstewart/stm/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2018-01-28 18:42:14 UTC; bms4
# Repository: CRAN
# Date/Publication: 2018-01-28 21:13:01 UTC
